name: pysmap
dependencies:
- python=3.6
- bokeh
- pytz
- pandas
- pip:
  - smappdragon>=0.0.41
  - langdetect>=1.0.6
  - stop-words>=2015.2.23.1
  - networkx>=1.11
  - pymongo>=3.2.2
  - matplotlib>=2.0.0
  - keras>=2.0.8
  - python-opencv>=3.3.0.9
  - tensorflow>=1.3.0
  - h5py>=2.7.0